### ISSUE TITLE
Is there any improvements of this project?

### ISSUE THREAD

**Issue by dongzhenye** [jhallard/BioSig-for-Android#1]
I am happy to see your repo on GitHub, but this work is not finished. Can you tell me the latest updates of this research? Thanks ahead.

**Comment by jhallard** [comment]
I actually haven't spent any time on improving it. It was developed while I was doing research at an institution and when that research ended, I lost my ability to access the shimmer sensing devices that the program is built around.

**Comment by dongzhenye** [comment]
We just bought several shimmer EXG devices, and it looks like I have to come up with other ideas to handle them. Please notify me if you have any other useful imformations about ECG in the future. Any way, thank you all the same!
